profile: 'security'
format: 1.0
fvc: "46564332008de01dcc150bcf6673a576d4c438b442afbb61d2cc98017234e44d9e338f19e8"
## ----------------------------------------------------
##                 CVEs
## ----------------------------------------------------
cve_list:
  ## cve
  - cve_id: 'CVE-2022-30065'
    description: |
      Dummy profile
    status: 'Open'
    date: null
    link: null
    comments: |
      patch is available
    references: []
  ## -----------------
  ## cve
  ## -----------------
  - cve_id: 'CVE-2022-28391'
    description: |
      Dummy
    status: 'open'
    date: null
    comments: null
    link: null
    references: []
