## Purpose: Configuration file for the ccli utility 
##
##
## catalog address
server_addr: "http://aws-ip-services-frontdoor-dev.wrs.com"
server_port: 8080
##
## logging
log_file: '__msg_log.csv'
log_level: 1
##
##
## How much to indent the json format of an output file.
json_indent: 2