## Purpose: Configuration file for the ccli utility 
##
##
## catalog address
server_addr: "http://localhost/api/graphql"
##
## logging
## there are 2 log levels:
## 1 - debugger
## 2 - debugger with source data
log_file: "log.txt"
log_level: 1
##
##
## How much to indent the json format of an output file.
json_indent: 2