## Purpose: Configuration file for the ccli utility 
##
##
## catalog address
server_addr: "https://aws-ip-services-tk-dev.wrs.com/api/graphql"
server_port: 443
##
## logging
log_file: 'log.txt'
log_level: 2
##
##
## How much to indent the json format of an output file.
json_indent: 2